input {
  file {
    path => "/usr/share/logstash/sample.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  grok {
    match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} \[%{DATA:thread}\] %{GREEDYDATA:log_message}" }
  }
}

output {
  elasticsearch {
    hosts => ["https://ecp-elasticsearch:9200"]
    user => "elastic"
    password => "${ELASTIC_PASSWORD}"
    ssl_certificate_authorities => "/usr/share/logstash/config/certs/ca/ca.crt"
    index => "sample-logs-%{+YYYY.MM.dd}"
  }
  stdout { 
    codec => rubydebug 
  }
}
